include_guard(GLOBAL)
add_subdirectory(
  $ENV{FORGE_ROOT}/firmware
  ${CMAKE_BINARY_DIR}/forge/firmware
)
add_subdirectory(
  $ENV{FORGE_ROOT}/test/native
  ${CMAKE_BINARY_DIR}/forge/test/native
)
add_subdirectory(
  $ENV{FORGE_ROOT}/test/common
  ${CMAKE_BINARY_DIR}/forge/test/common
)
