"""SVD → C++ register headers, generated by forge as a build action."""

load("@rules_cc//cc:defs.bzl", "cc_library")

def svd_cc_library(name, svd, include_prefix = "", deps = [], **kwargs):
    """Generates register headers from an SVD file and exposes them as a cc_library.

    Args:
      name: Library name.
      svd: SVD file to generate from.
      include_prefix: Directory the headers are included under, e.g. "registers" for
        `#include "registers/gpio.hpp"`.
      deps: Libraries the headers depend on.
      **kwargs: Forwarded to the cc_library.
    """
    headers = name + "_headers"
    _svd_headers(
        name = headers,
        svd = svd,
        include_prefix = include_prefix,
    )
    cc_library(
        name = name,
        hdrs = [":" + headers],
        includes = [headers],
        deps = deps,
        **kwargs
    )

def _svd_headers_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    ctx.actions.run(
        executable = ctx.executable._generator,
        arguments = [ctx.file.svd.path, out.path + "/" + ctx.attr.include_prefix],
        inputs = [ctx.file.svd],
        outputs = [out],
        mnemonic = "SvdGen",
        progress_message = "Generating register headers from %{input}",
    )
    return [DefaultInfo(files = depset([out]))]

_svd_headers = rule(
    implementation = _svd_headers_impl,
    attrs = {
        "svd": attr.label(allow_single_file = True, mandatory = True),
        "include_prefix": attr.string(),
        "_generator": attr.label(
            default = "//tools:svd_generate",
            executable = True,
            cfg = "exec",
        ),
    },
)
