[tox]
envlist = py312
minversion = 3.24      # Minimum tox version required

[testenv]
description = Run tests using Poetry
allowlist_externals = poetry  # Allow Poetry commands in tox
deps = 
    pytest  # Include your test dependencies if needed
commands =
    ; poetry install --no-root --with dev  # Install dependencies defined in pyproject.toml
    poetry --directory ./scripts/package run pytest {posargs}
    
