[project]
name = "forge"
version = "0.1.0"
description = "Embedded tooling"
authors = [{name = "Jacob", email = "jacob.heathorn@gmail.com"}]
requires-python = ">=3.12"
dependencies = [
    "semver>=3.0.1",
    "gitpython",
    "jinja2",
    "json5",
    "cmsis-svd==0.6.0",
    "pyserial",
]

[tool.pytest.ini_options]
cache_dir = "../../.pycache"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"