load("//bazel:cc.bzl", "forge_cc_library")

forge_cc_library(
    name = "ftl-native",
    srcs = [
        "native_ethernet_interface.cpp",
        "native_udp_socket.cpp",
    ],
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["//firmware/ftl"],
)

exports_files(["pw_ut_main.cpp"])
