#include "gtest/gtest.h"

#include <sys/mman.h>
#include <cstdint>
#include <cstring>

// Generated by forge from ./test_peripheral.svd at build time.
#include "testperiph.hpp"
#include "port.hpp"

namespace periph = regs::testperiph;

// Peripheral base from the fixture SVD. A 16 KB scratch span is mmap'd here
// with MAP_FIXED at test-suite startup so Register addresses are backed by
// real memory. Span covers TESTPERIPH (0x10000000) + the PORT family
// (PORT1=0x10001000, PORT2=0x10001100, PORT3=0x10001200).
constexpr std::uintptr_t kPeriphBase  = 0x10000000u;
constexpr std::size_t    kPeriphBytes = 16 * 1024u;

inline std::uint8_t* periphBytes() {
  return reinterpret_cast<std::uint8_t*>(kPeriphBase);
}

class MmioTest : public ::testing::Test {
 protected:
  static void SetUpTestSuite() {
    void* p = ::mmap(reinterpret_cast<void*>(kPeriphBase),
                     kPeriphBytes,
                     PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED,
                     -1, 0);
    ASSERT_NE(p, MAP_FAILED);
    ASSERT_EQ(reinterpret_cast<std::uintptr_t>(p), kPeriphBase);
  }
  static void TearDownTestSuite() {
    ::munmap(reinterpret_cast<void*>(kPeriphBase), kPeriphBytes);
  }
  void SetUp() override {
    std::memset(periphBytes(), 0, kPeriphBytes);
  }
};

// --- 32-bit register ---------------------------------------------------------

TEST_F(MmioTest, WriteReadRoundtripStatus) {
  periph::STATUS::write(
      periph::STATUS::READY{true},
      periph::STATUS::MODE{periph::STATUS::eMODE::eACTIVE},
      periph::STATUS::COUNT{std::uint8_t{0x42}});

  auto snap = periph::STATUS::read();
  EXPECT_TRUE(snap.get<periph::STATUS::READY>());
  EXPECT_EQ(snap.get<periph::STATUS::MODE>(), periph::STATUS::eMODE::eACTIVE);
  EXPECT_EQ(snap.get<periph::STATUS::COUNT>(), 0x42u);
}

TEST_F(MmioTest, ResetWritesResetValue) {
  periph::STATUS::write(
      periph::STATUS::READY{false},
      periph::STATUS::COUNT{std::uint8_t{0xAA}});
  periph::STATUS::reset();
  EXPECT_EQ(periph::STATUS::raw(), 0x00000001u);   // SVD resetValue
}

TEST_F(MmioTest, ModifyPreservesOtherFields) {
  periph::STATUS::write(
      periph::STATUS::READY{true},
      periph::STATUS::COUNT{std::uint8_t{0x55}});
  periph::STATUS::modify(periph::STATUS::MODE{periph::STATUS::eMODE::eSLEEP});

  auto snap = periph::STATUS::read();
  EXPECT_TRUE(snap.get<periph::STATUS::READY>());
  EXPECT_EQ(snap.get<periph::STATUS::COUNT>(), 0x55u);
  EXPECT_EQ(snap.get<periph::STATUS::MODE>(), periph::STATUS::eMODE::eSLEEP);
}

// --- W1C semantics -----------------------------------------------------------
//
// mmap'd RAM is plain memory: writing 0 to a W1C bit on RAM stores 0, but on
// real hardware it would be a no-op. These tests assert the *write pattern*
// the software emits, which is what the abstraction controls.

TEST_F(MmioTest, W1cClearEmitsOnlyTargetBit) {
  // FLAGS is pure-W1C (no normal RW, no reserved), so clear<>() bypasses RMW
  // and writes the mask directly. We verify the exact word written.
  periph::FLAGS::clear<periph::FLAGS::OVERFLOW>();
  EXPECT_EQ(periph::FLAGS::raw(), 1u << 0);
}

TEST_F(MmioTest, W1cClearMultipleFields) {
  periph::FLAGS::clear<periph::FLAGS::OVERFLOW, periph::FLAGS::UNDERFLOW>();
  EXPECT_EQ(periph::FLAGS::raw(), (1u << 0) | (1u << 1));
}

TEST_F(MmioTest, ModifyNeutralizesW1cBitsOnMixedRegister) {
  // COUNTER has VALUE (normal RW, bits 0..15) and SATURATED (W1C, bit 31).
  // modify(VALUE{...}) must update VALUE and write 0 to SATURATED so the
  // RMW doesn't re-trigger it on hardware. On RAM we observe SATURATED as 0.
  periph::COUNTER::raw() = 0x1234u | (1u << 31);
  periph::COUNTER::modify(periph::COUNTER::VALUE{std::uint16_t{0x5678}});
  EXPECT_EQ(periph::COUNTER::raw() & 0xFFFFu,   0x5678u);  // VALUE updated
  EXPECT_EQ(periph::COUNTER::raw() & (1u << 31), 0u);      // W1C neutralized
}

// --- 16-bit register ---------------------------------------------------------

TEST_F(MmioTest, SixteenBitRegisterUsesHalfwordStore) {
  // Seed flanking bytes; a well-formed 16-bit store must not disturb them.
  periphBytes()[0x0A] = 0xAA;                      // unused gap
  // CONTROL sits at offset 0x08..0x09, so bytes at 0x0A/0x0B are outside.
  periph::CONTROL::write(
      periph::CONTROL::ENABLE{true},
      periph::CONTROL::SCALE{std::uint8_t{0x5}});
  EXPECT_EQ(periphBytes()[0x0A], 0xAAu);
  auto snap = periph::CONTROL::read();
  EXPECT_TRUE(snap.get<periph::CONTROL::ENABLE>());
  EXPECT_EQ(snap.get<periph::CONTROL::SCALE>(), 0x5u);
}

// --- 8-bit register at unaligned offset (the SERQ regression guard) ---------

TEST_F(MmioTest, EightBitRegisterAtUnalignedOffsetIsByteStore) {
  // TRIGGER sits at offset 0x0B — three bytes into a 32-bit word. Flanking
  // bytes must survive every write to TRIGGER; if the generator regresses to
  // uint32_t storage for this register we'd stomp 0x0B..0x0E.
  std::memset(periphBytes(), 0xFF, kPeriphBytes);

  periph::TRIGGER::write(periph::TRIGGER::CHANNEL{std::uint8_t{0x05}});

  EXPECT_EQ(periphBytes()[0x0A], 0xFFu);           // before
  EXPECT_EQ(periphBytes()[0x0B], 0x05u);           // our write
  EXPECT_EQ(periphBytes()[0x0C], 0xFFu);           // after — would be clobbered
  EXPECT_EQ(periphBytes()[0x0D], 0xFFu);           //   by a 32-bit store at 0x0B
  EXPECT_EQ(periphBytes()[0x0E], 0xFFu);
}

TEST_F(MmioTest, EightBitResetValue) {
  periphBytes()[0x0B] = 0xFF;
  periph::TRIGGER::reset();
  EXPECT_EQ(periphBytes()[0x0B], 0x00u);
}

// --- Read-only / write-only access (compile-time policy) ---------------------

TEST_F(MmioTest, ReadOnlyRegisterSnapshot) {
  // VERSION is RO. We poke the backing memory directly; Register::read()
  // then returns a Snapshot without ever writing.
  *reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x0C) = 0x00030004u;
  auto snap = periph::VERSION::read();
  EXPECT_EQ(snap.get<periph::VERSION::MINOR>(), 0x0004u);
  EXPECT_EQ(snap.get<periph::VERSION::MAJOR>(), 0x0003u);
}

TEST_F(MmioTest, WriteOnlyRegisterWrite) {
  periph::COMMAND::write(
      periph::COMMAND::OPCODE {std::uint8_t { 0x12}},
      periph::COMMAND::PAYLOAD{std::uint32_t{0xABCDEFu}});
  EXPECT_EQ(*reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x10),
            (0xABCDEFu << 8) | 0x12u);
}

// --- Storage-type sanity check ----------------------------------------------

TEST_F(MmioTest, StorageTypesMatchSvdSize) {
  static_assert(std::is_same_v<periph::STATUS::storage_type,  std::uint32_t>);
  static_assert(std::is_same_v<periph::CONTROL::storage_type, std::uint16_t>);
  static_assert(std::is_same_v<periph::TRIGGER::storage_type, std::uint8_t>);
}

// --- Register array (single register replicated by <dim>) ------------------
//
// SLOT[N] in the fixture: 4 instances at peripheral offsets 0x20, 0x24, 0x28,
// 0x2C. Single VALUE field covering all 32 bits.

TEST_F(MmioTest, RegisterArrayAddressesAreCorrect) {
  EXPECT_EQ(periph::SLOT<0>::kAddr, 0x10000020u);
  EXPECT_EQ(periph::SLOT<1>::kAddr, 0x10000024u);
  EXPECT_EQ(periph::SLOT<2>::kAddr, 0x10000028u);
  EXPECT_EQ(periph::SLOT<3>::kAddr, 0x1000002Cu);
}

TEST_F(MmioTest, RegisterArrayWriteIsolatedPerIndex) {
  periph::SLOT<0>::write(periph::SLOT<0>::VALUE{0xAAAAAAAAu});
  periph::SLOT<2>::write(periph::SLOT<2>::VALUE{0x12345678u});
  EXPECT_EQ(periph::SLOT<0>::read().get<periph::SLOT<0>::VALUE>(), 0xAAAAAAAAu);
  EXPECT_EQ(periph::SLOT<1>::read().get<periph::SLOT<1>::VALUE>(), 0u);  // untouched
  EXPECT_EQ(periph::SLOT<2>::read().get<periph::SLOT<2>::VALUE>(), 0x12345678u);
  EXPECT_EQ(periph::SLOT<3>::read().get<periph::SLOT<3>::VALUE>(), 0u);  // untouched
}

// --- Cluster array (templated index) -----------------------------------------
//
// Fixture: peripheral has a cluster of 4 channels, dim_increment=0x10, starting
// at peripheral offset 0x40. CHAN_CONFIG (32-bit) at intra-cluster offset 0,
// CHAN_STATE (8-bit) at intra-cluster offset 0x8.

TEST_F(MmioTest, ClusterAddressesAreCorrectPerIndex) {
  // Channel 0: 0x10000040 (CONFIG), 0x10000048 (STATE)
  // Channel 1: 0x10000050,           0x10000058
  // Channel 2: 0x10000060,           0x10000068
  // Channel 3: 0x10000070,           0x10000078
  EXPECT_EQ(periph::CHAN_CONFIG<0>::kAddr, 0x10000040u);
  EXPECT_EQ(periph::CHAN_CONFIG<1>::kAddr, 0x10000050u);
  EXPECT_EQ(periph::CHAN_CONFIG<2>::kAddr, 0x10000060u);
  EXPECT_EQ(periph::CHAN_CONFIG<3>::kAddr, 0x10000070u);
  EXPECT_EQ(periph::CHAN_STATE<0>::kAddr,  0x10000048u);
  EXPECT_EQ(periph::CHAN_STATE<3>::kAddr,  0x10000078u);
}

TEST_F(MmioTest, ClusterWriteIsolatedPerChannel) {
  periph::CHAN_CONFIG<0>::write(periph::CHAN_CONFIG<0>::SOURCE{std::uint8_t{0xAA}});
  periph::CHAN_CONFIG<2>::write(periph::CHAN_CONFIG<2>::SOURCE{std::uint8_t{0xCC}});
  EXPECT_EQ(periph::CHAN_CONFIG<0>::read().get<periph::CHAN_CONFIG<0>::SOURCE>(), 0xAAu);
  EXPECT_EQ(periph::CHAN_CONFIG<1>::read().get<periph::CHAN_CONFIG<1>::SOURCE>(), 0u);  // untouched
  EXPECT_EQ(periph::CHAN_CONFIG<2>::read().get<periph::CHAN_CONFIG<2>::SOURCE>(), 0xCCu);
  EXPECT_EQ(periph::CHAN_CONFIG<3>::read().get<periph::CHAN_CONFIG<3>::SOURCE>(), 0u);  // untouched
}

TEST_F(MmioTest, ClusterEightBitStateIsByteStore) {
  // CHAN_STATE<1> is at 0x10000058 — only that byte may change.
  std::memset(periphBytes(), 0xFF, kPeriphBytes);
  periph::CHAN_STATE<1>::write(periph::CHAN_STATE<1>::VALUE{std::uint8_t{0x42}});
  EXPECT_EQ(periphBytes()[0x57], 0xFFu);
  EXPECT_EQ(periphBytes()[0x58], 0x42u);
  EXPECT_EQ(periphBytes()[0x59], 0xFFu);
  EXPECT_EQ(periphBytes()[0x5A], 0xFFu);
  EXPECT_EQ(periphBytes()[0x5B], 0xFFu);
}

TEST_F(MmioTest, ClusterStorageTypesMatchSvdSize) {
  static_assert(std::is_same_v<periph::CHAN_CONFIG<0>::storage_type, std::uint32_t>);
  static_assert(std::is_same_v<periph::CHAN_STATE<0>::storage_type,  std::uint8_t>);
}

// --- Nested register array inside cluster array (2D template) ---------------
//
// Fixture: each channel cluster (CHAN[0..3]) contains a CHAN_SETPOINT[0..1]
// array at intra-cluster offset 0xC, dim_increment 4. So:
//   CHAN_SETPOINT<C, S>::kAddr = 0x10000040 + (C * 0x10) + 0xC + (S * 0x4)
// Channel 0: 0x1000004C, 0x10000050
// Channel 1: 0x1000005C, 0x10000060
// Channel 2: 0x1000006C, 0x10000070
// Channel 3: 0x1000007C, ... wait — CHAN_SETPOINT<3,1> would be 0x10000080,
// which is past the addressBlock; addressBlock is 0x80 sized so 0x10000080
// is just past the end. That's fine for the test — the addresses are still
// inside the mmap'd 4 KB scratch page.

TEST_F(MmioTest, NestedArrayAddressesAreCorrect) {
  EXPECT_EQ((periph::CHAN_SETPOINT<0, 0>::kAddr), 0x1000004Cu);
  EXPECT_EQ((periph::CHAN_SETPOINT<0, 1>::kAddr), 0x10000050u);
  EXPECT_EQ((periph::CHAN_SETPOINT<1, 0>::kAddr), 0x1000005Cu);
  EXPECT_EQ((periph::CHAN_SETPOINT<2, 1>::kAddr), 0x10000070u);
  EXPECT_EQ((periph::CHAN_SETPOINT<3, 1>::kAddr), 0x10000080u);
}

// --- Peripheral family (derivedFrom -> templated class) ---------------------
//
// Fixture: PORT1 (canonical) at 0x10001000, PORT2 derivedFrom PORT1 at
// 0x10001100, PORT3 at 0x10001200. The generator emits one
// `template<u32 Instance> struct Port` covering all three.

TEST_F(MmioTest, FamilyAddressesAreCorrectPerInstance) {
  EXPECT_EQ((regs::Port<1>::CTRL::kAddr), 0x10001000u);
  EXPECT_EQ((regs::Port<2>::CTRL::kAddr), 0x10001100u);
  EXPECT_EQ((regs::Port<3>::CTRL::kAddr), 0x10001200u);
  EXPECT_EQ((regs::Port<1>::DATA::kAddr), 0x10001004u);
  EXPECT_EQ((regs::Port<3>::DATA::kAddr), 0x10001204u);
}

TEST_F(MmioTest, FamilyWriteIsolatedPerInstance) {
  using p1 = regs::Port<1>;
  using p2 = regs::Port<2>;
  using p3 = regs::Port<3>;

  p1::CTRL::write(p1::CTRL::ENABLE{true}, p1::CTRL::MODE{std::uint8_t{0x5}});
  p3::DATA::write(p3::DATA::VALUE{0xDEADBEEFu});

  EXPECT_TRUE (p1::CTRL::read().get<p1::CTRL::ENABLE>());
  EXPECT_EQ   (p1::CTRL::read().get<p1::CTRL::MODE>(), 0x5u);
  EXPECT_FALSE(p2::CTRL::read().get<p2::CTRL::ENABLE>());     // untouched
  EXPECT_EQ   (p2::DATA::read().get<p2::DATA::VALUE>(), 0u);  // untouched
  EXPECT_EQ   (p3::DATA::read().get<p3::DATA::VALUE>(), 0xDEADBEEFu);
}

TEST_F(MmioTest, FamilyStorageTypeMatchesSvd) {
  static_assert(std::is_same_v<regs::Port<1>::CTRL::storage_type, std::uint32_t>);
  static_assert(std::is_same_v<regs::Port<2>::DATA::storage_type, std::uint32_t>);
}

TEST_F(MmioTest, NestedArrayWriteIsolatedPerCellOfTwoDimensions) {
  using s00 = periph::CHAN_SETPOINT<0, 0>;
  using s01 = periph::CHAN_SETPOINT<0, 1>;
  using s10 = periph::CHAN_SETPOINT<1, 0>;
  using s11 = periph::CHAN_SETPOINT<1, 1>;

  s00::write(s00::POINT{0xAA000000u});
  s11::write(s11::POINT{0x000000BBu});
  EXPECT_EQ(s00::read().get<s00::POINT>(), 0xAA000000u);
  EXPECT_EQ(s01::read().get<s01::POINT>(), 0u);             // untouched
  EXPECT_EQ(s10::read().get<s10::POINT>(), 0u);             // untouched
  EXPECT_EQ(s11::read().get<s11::POINT>(), 0x000000BBu);
}
