#include "gtest/gtest.h"

#include <sys/mman.h>
#include <cstdint>
#include <cstring>

// Generated by forge from ./test_peripheral.svd at build time.
#include "testperiph.hpp"

namespace periph = regs::testperiph;

// Peripheral base from the fixture SVD. A 4 KB scratch page is mmap'd here
// with MAP_FIXED at test-suite startup so Register addresses are backed by
// real memory.
constexpr std::uintptr_t kPeriphBase  = 0x10000000u;
constexpr std::size_t    kPeriphBytes = 4096u;

inline std::uint8_t* periphBytes() {
  return reinterpret_cast<std::uint8_t*>(kPeriphBase);
}

class MmioTest : public ::testing::Test {
 protected:
  static void SetUpTestSuite() {
    void* p = ::mmap(reinterpret_cast<void*>(kPeriphBase),
                     kPeriphBytes,
                     PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED,
                     -1, 0);
    ASSERT_NE(p, MAP_FAILED);
    ASSERT_EQ(reinterpret_cast<std::uintptr_t>(p), kPeriphBase);
  }
  static void TearDownTestSuite() {
    ::munmap(reinterpret_cast<void*>(kPeriphBase), kPeriphBytes);
  }
  void SetUp() override {
    std::memset(periphBytes(), 0, kPeriphBytes);
  }
};

// --- 32-bit register ---------------------------------------------------------

TEST_F(MmioTest, WriteReadRoundtripStatus) {
  periph::STATUS::write(
      periph::STATUS::READY{true},
      periph::STATUS::MODE{periph::STATUS::eMODE::eACTIVE},
      periph::STATUS::COUNT{std::uint8_t{0x42}});

  auto snap = periph::STATUS::read();
  EXPECT_TRUE(snap.get<periph::STATUS::READY>());
  EXPECT_EQ(snap.get<periph::STATUS::MODE>(), periph::STATUS::eMODE::eACTIVE);
  EXPECT_EQ(snap.get<periph::STATUS::COUNT>(), 0x42u);
}

TEST_F(MmioTest, ResetWritesResetValue) {
  periph::STATUS::write(
      periph::STATUS::READY{false},
      periph::STATUS::COUNT{std::uint8_t{0xAA}});
  periph::STATUS::reset();
  EXPECT_EQ(periph::STATUS::raw(), 0x00000001u);   // SVD resetValue
}

TEST_F(MmioTest, ModifyPreservesOtherFields) {
  periph::STATUS::write(
      periph::STATUS::READY{true},
      periph::STATUS::COUNT{std::uint8_t{0x55}});
  periph::STATUS::modify(periph::STATUS::MODE{periph::STATUS::eMODE::eSLEEP});

  auto snap = periph::STATUS::read();
  EXPECT_TRUE(snap.get<periph::STATUS::READY>());
  EXPECT_EQ(snap.get<periph::STATUS::COUNT>(), 0x55u);
  EXPECT_EQ(snap.get<periph::STATUS::MODE>(), periph::STATUS::eMODE::eSLEEP);
}

// --- W1C semantics -----------------------------------------------------------
//
// mmap'd RAM is plain memory: writing 0 to a W1C bit on RAM stores 0, but on
// real hardware it would be a no-op. These tests assert the *write pattern*
// the software emits, which is what the abstraction controls.

TEST_F(MmioTest, W1cClearEmitsOnlyTargetBit) {
  // FLAGS is pure-W1C (no normal RW, no reserved), so clear<>() bypasses RMW
  // and writes the mask directly. We verify the exact word written.
  periph::FLAGS::clear<periph::FLAGS::OVERFLOW>();
  EXPECT_EQ(periph::FLAGS::raw(), 1u << 0);
}

TEST_F(MmioTest, W1cClearMultipleFields) {
  periph::FLAGS::clear<periph::FLAGS::OVERFLOW, periph::FLAGS::UNDERFLOW>();
  EXPECT_EQ(periph::FLAGS::raw(), (1u << 0) | (1u << 1));
}

TEST_F(MmioTest, ModifyNeutralizesW1cBitsOnMixedRegister) {
  // COUNTER has VALUE (normal RW, bits 0..15) and SATURATED (W1C, bit 31).
  // modify(VALUE{...}) must update VALUE and write 0 to SATURATED so the
  // RMW doesn't re-trigger it on hardware. On RAM we observe SATURATED as 0.
  periph::COUNTER::raw() = 0x1234u | (1u << 31);
  periph::COUNTER::modify(periph::COUNTER::VALUE{std::uint16_t{0x5678}});
  EXPECT_EQ(periph::COUNTER::raw() & 0xFFFFu,   0x5678u);  // VALUE updated
  EXPECT_EQ(periph::COUNTER::raw() & (1u << 31), 0u);      // W1C neutralized
}

// --- 16-bit register ---------------------------------------------------------

TEST_F(MmioTest, SixteenBitRegisterUsesHalfwordStore) {
  // Seed flanking bytes; a well-formed 16-bit store must not disturb them.
  periphBytes()[0x0A] = 0xAA;                      // unused gap
  // CONTROL sits at offset 0x08..0x09, so bytes at 0x0A/0x0B are outside.
  periph::CONTROL::write(
      periph::CONTROL::ENABLE{true},
      periph::CONTROL::SCALE{std::uint8_t{0x5}});
  EXPECT_EQ(periphBytes()[0x0A], 0xAAu);
  auto snap = periph::CONTROL::read();
  EXPECT_TRUE(snap.get<periph::CONTROL::ENABLE>());
  EXPECT_EQ(snap.get<periph::CONTROL::SCALE>(), 0x5u);
}

// --- 8-bit register at unaligned offset (the SERQ regression guard) ---------

TEST_F(MmioTest, EightBitRegisterAtUnalignedOffsetIsByteStore) {
  // TRIGGER sits at offset 0x0B — three bytes into a 32-bit word. Flanking
  // bytes must survive every write to TRIGGER; if the generator regresses to
  // uint32_t storage for this register we'd stomp 0x0B..0x0E.
  std::memset(periphBytes(), 0xFF, kPeriphBytes);

  periph::TRIGGER::write(periph::TRIGGER::CHANNEL{std::uint8_t{0x05}});

  EXPECT_EQ(periphBytes()[0x0A], 0xFFu);           // before
  EXPECT_EQ(periphBytes()[0x0B], 0x05u);           // our write
  EXPECT_EQ(periphBytes()[0x0C], 0xFFu);           // after — would be clobbered
  EXPECT_EQ(periphBytes()[0x0D], 0xFFu);           //   by a 32-bit store at 0x0B
  EXPECT_EQ(periphBytes()[0x0E], 0xFFu);
}

TEST_F(MmioTest, EightBitResetValue) {
  periphBytes()[0x0B] = 0xFF;
  periph::TRIGGER::reset();
  EXPECT_EQ(periphBytes()[0x0B], 0x00u);
}

// --- Read-only / write-only access (compile-time policy) ---------------------

TEST_F(MmioTest, ReadOnlyRegisterSnapshot) {
  // VERSION is RO. We poke the backing memory directly; Register::read()
  // then returns a Snapshot without ever writing.
  *reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x0C) = 0x00030004u;
  auto snap = periph::VERSION::read();
  EXPECT_EQ(snap.get<periph::VERSION::MINOR>(), 0x0004u);
  EXPECT_EQ(snap.get<periph::VERSION::MAJOR>(), 0x0003u);
}

TEST_F(MmioTest, WriteOnlyRegisterWrite) {
  periph::COMMAND::write(
      periph::COMMAND::OPCODE {std::uint8_t { 0x12}},
      periph::COMMAND::PAYLOAD{std::uint32_t{0xABCDEFu}});
  EXPECT_EQ(*reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x10),
            (0xABCDEFu << 8) | 0x12u);
}

// --- Storage-type sanity check ----------------------------------------------

TEST_F(MmioTest, StorageTypesMatchSvdSize) {
  static_assert(std::is_same_v<periph::STATUS::storage_type,  std::uint32_t>);
  static_assert(std::is_same_v<periph::CONTROL::storage_type, std::uint16_t>);
  static_assert(std::is_same_v<periph::TRIGGER::storage_type, std::uint8_t>);
}
