#include "gtest/gtest.h"

#include <sys/mman.h>
#include <cstdint>
#include <cstring>

// Generated by forge from ./test_peripheral.svd at build time.
#include "testperiph.hpp"
#include "port.hpp"

namespace periph = regs::testperiph;

// 16 KB scratch span mmap'd at the fixture peripheral base so Register<>
// addresses resolve to real memory. Covers TESTPERIPH (0x10000000) and the
// PORT family (0x10001000..0x100012FF).
constexpr std::uintptr_t kPeriphBase  = 0x10000000u;
constexpr std::size_t    kPeriphBytes = 16 * 1024u;

inline std::uint8_t* periphBytes() {
  return reinterpret_cast<std::uint8_t*>(kPeriphBase);
}

class MmioTest : public ::testing::Test {
 protected:
  static void SetUpTestSuite() {
    void* p = ::mmap(reinterpret_cast<void*>(kPeriphBase), kPeriphBytes,
                     PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0);
    ASSERT_NE(p, MAP_FAILED);
    ASSERT_EQ(reinterpret_cast<std::uintptr_t>(p), kPeriphBase);
  }
  static void TearDownTestSuite() {
    ::munmap(reinterpret_cast<void*>(kPeriphBase), kPeriphBytes);
  }
  void SetUp() override { std::memset(periphBytes(), 0, kPeriphBytes); }
};

// --- Plain 32-bit register ---------------------------------------------------

TEST_F(MmioTest, WriteThenReadRoundtrip) {
  using Status = periph::STATUS;
  Status::write(Status::READY{true},
                Status::MODE  {Status::eMODE::eACTIVE},
                Status::COUNT {std::uint8_t{0x42}});

  auto snap = Status::read();
  EXPECT_TRUE(snap.get<Status::READY>());
  EXPECT_EQ  (snap.get<Status::MODE>(),  Status::eMODE::eACTIVE);
  EXPECT_EQ  (snap.get<Status::COUNT>(), 0x42u);
}

TEST_F(MmioTest, ResetWritesSvdResetValue) {
  using Status = periph::STATUS;
  Status::write(Status::READY{false}, Status::COUNT{std::uint8_t{0xAA}});
  Status::reset();
  EXPECT_EQ(Status::raw(), 0x00000001u);
}

TEST_F(MmioTest, ModifyPreservesUnspecifiedFields) {
  using Status = periph::STATUS;
  Status::write(Status::READY{true}, Status::COUNT{std::uint8_t{0x55}});
  Status::modify(Status::MODE{Status::eMODE::eSLEEP});

  auto snap = Status::read();
  EXPECT_TRUE(snap.get<Status::READY>());
  EXPECT_EQ  (snap.get<Status::COUNT>(), 0x55u);
  EXPECT_EQ  (snap.get<Status::MODE>(),  Status::eMODE::eSLEEP);
}

// --- Modify-write semantics: W1C / W1S / W1T --------------------------------
//
// mmap'd RAM doesn't honor W1C/W1S/W1T (any write just stores). These tests
// assert the *write pattern* the abstraction emits — what the software puts
// on the bus. Hardware then applies its modify-write semantics.

TEST_F(MmioTest, ClearEmitsOnlyTargetBit) {
  using Flags = periph::FLAGS;
  Flags::clear<Flags::OVERFLOW>();
  EXPECT_EQ(Flags::raw(), 1u << 0);
}

TEST_F(MmioTest, ClearMultipleFieldsCombinesMasks) {
  using Flags = periph::FLAGS;
  Flags::clear<Flags::OVERFLOW, Flags::UNDERFLOW>();
  EXPECT_EQ(Flags::raw(), (1u << 0) | (1u << 1));
}

TEST_F(MmioTest, SetEmitsOnlyTargetBit) {
  using Flags = periph::FLAGS;
  Flags::set<Flags::LATCH>();
  EXPECT_EQ(Flags::raw(), 1u << 8);
}

TEST_F(MmioTest, ToggleEmitsOnlyTargetBit) {
  using Flags = periph::FLAGS;
  Flags::toggle<Flags::PULSE>();
  EXPECT_EQ(Flags::raw(), 1u << 16);
}

TEST_F(MmioTest, ClearLeavesOtherSensitiveFlagsUntouched) {
  // Even when W1C/W1S/W1T fields share a register, clear<W1C> must write 0
  // to the W1S/W1T positions so they don't fire on hardware.
  using Flags = periph::FLAGS;
  Flags::raw() = 0xFFFFFFFFu;  // all bits set in backing memory
  Flags::clear<Flags::OVERFLOW>();
  EXPECT_EQ(Flags::raw() & (1u << 8),  0u);  // LATCH (W1S) written as 0
  EXPECT_EQ(Flags::raw() & (1u << 16), 0u);  // PULSE (W1T) written as 0
  EXPECT_EQ(Flags::raw() & (1u << 0),  1u << 0);  // OVERFLOW: the clear bit
}

TEST_F(MmioTest, ModifyZerosW1cBitsOnMixedRegister) {
  // COUNTER mixes a normal RW field (VALUE) with a W1C flag (SATURATED).
  // modify(VALUE{...}) must store 0 to SATURATED so it isn't re-triggered.
  using Counter = periph::COUNTER;
  Counter::raw() = 0x1234u | (1u << 31);
  Counter::modify(Counter::VALUE{std::uint16_t{0x5678}});

  EXPECT_EQ(Counter::raw() & 0xFFFFu,    0x5678u);
  EXPECT_EQ(Counter::raw() & (1u << 31), 0u);
}

// --- Storage width: 8 / 16 / 32-bit MMIO accesses ---------------------------

TEST_F(MmioTest, SixteenBitRegisterDoesNotDisturbFlankingBytes) {
  // CONTROL is 2 bytes at offset 0x08. A correct halfword store must leave
  // bytes at 0x0A onward alone.
  periphBytes()[0x0A] = 0xAA;

  using Control = periph::CONTROL;
  Control::write(Control::ENABLE{true}, Control::SCALE{std::uint8_t{0x5}});

  EXPECT_EQ(periphBytes()[0x0A], 0xAAu);
  auto snap = Control::read();
  EXPECT_TRUE(snap.get<Control::ENABLE>());
  EXPECT_EQ  (snap.get<Control::SCALE>(), 0x5u);
}

TEST_F(MmioTest, EightBitRegisterAtUnalignedOffsetIsByteStore) {
  // TRIGGER lives at byte offset 0x0B. If storage regresses to uint32_t the
  // store would smear across 0x0B..0x0E (this is the SERQ regression guard).
  std::memset(periphBytes(), 0xFF, kPeriphBytes);
  periph::TRIGGER::write(periph::TRIGGER::CHANNEL{std::uint8_t{0x05}});

  EXPECT_EQ(periphBytes()[0x0A], 0xFFu);
  EXPECT_EQ(periphBytes()[0x0B], 0x05u);
  EXPECT_EQ(periphBytes()[0x0C], 0xFFu);
  EXPECT_EQ(periphBytes()[0x0D], 0xFFu);
  EXPECT_EQ(periphBytes()[0x0E], 0xFFu);
}

TEST_F(MmioTest, EightBitResetWritesByteResetValue) {
  periphBytes()[0x0B] = 0xFF;
  periph::TRIGGER::reset();
  EXPECT_EQ(periphBytes()[0x0B], 0x00u);
}

TEST_F(MmioTest, StorageTypesMatchSvdSize) {
  static_assert(std::is_same_v<periph::STATUS::storage_type,  std::uint32_t>);
  static_assert(std::is_same_v<periph::CONTROL::storage_type, std::uint16_t>);
  static_assert(std::is_same_v<periph::TRIGGER::storage_type, std::uint8_t>);
}

// --- Access policy ----------------------------------------------------------

TEST_F(MmioTest, ReadOnlyRegisterReturnsBackingBytes) {
  // VERSION is RO. Poke memory directly; read() returns a Snapshot of it.
  *reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x0C) = 0x00030004u;

  using Version = periph::VERSION;
  auto snap = Version::read();
  EXPECT_EQ(snap.get<Version::MINOR>(), 0x0004u);
  EXPECT_EQ(snap.get<Version::MAJOR>(), 0x0003u);
}

TEST_F(MmioTest, WriteOnlyRegisterStoresFieldsAtomically) {
  using Command = periph::COMMAND;
  Command::write(Command::OPCODE {std::uint8_t {0x12}},
                 Command::PAYLOAD{std::uint32_t{0xABCDEFu}});
  EXPECT_EQ(*reinterpret_cast<volatile std::uint32_t*>(kPeriphBase + 0x10),
            (0xABCDEFu << 8) | 0x12u);
}

// --- Register array: <register dim=N> -> templated by Index -----------------

TEST_F(MmioTest, RegisterArrayAddressArithmetic) {
  EXPECT_EQ(periph::SLOT<0>::kAddr, 0x10000020u);
  EXPECT_EQ(periph::SLOT<1>::kAddr, 0x10000024u);
  EXPECT_EQ(periph::SLOT<2>::kAddr, 0x10000028u);
  EXPECT_EQ(periph::SLOT<3>::kAddr, 0x1000002Cu);
}

TEST_F(MmioTest, RegisterArrayWritesAreIndexIsolated) {
  periph::SLOT<0>::write(periph::SLOT<0>::VALUE{0xAAAAAAAAu});
  periph::SLOT<2>::write(periph::SLOT<2>::VALUE{0x12345678u});

  EXPECT_EQ(periph::SLOT<0>::read().get<periph::SLOT<0>::VALUE>(), 0xAAAAAAAAu);
  EXPECT_EQ(periph::SLOT<1>::read().get<periph::SLOT<1>::VALUE>(), 0u);
  EXPECT_EQ(periph::SLOT<2>::read().get<periph::SLOT<2>::VALUE>(), 0x12345678u);
  EXPECT_EQ(periph::SLOT<3>::read().get<periph::SLOT<3>::VALUE>(), 0u);
}

// --- Cluster array: 4 channels, dim_increment=0x10 from offset 0x40 ---------

TEST_F(MmioTest, ClusterAddressArithmetic) {
  EXPECT_EQ(periph::CHAN_CONFIG<0>::kAddr, 0x10000040u);
  EXPECT_EQ(periph::CHAN_CONFIG<1>::kAddr, 0x10000050u);
  EXPECT_EQ(periph::CHAN_CONFIG<2>::kAddr, 0x10000060u);
  EXPECT_EQ(periph::CHAN_CONFIG<3>::kAddr, 0x10000070u);
  EXPECT_EQ(periph::CHAN_STATE<0>::kAddr,  0x10000048u);
  EXPECT_EQ(periph::CHAN_STATE<3>::kAddr,  0x10000078u);
}

TEST_F(MmioTest, ClusterWritesAreChannelIsolated) {
  using Cfg0 = periph::CHAN_CONFIG<0>;
  using Cfg1 = periph::CHAN_CONFIG<1>;
  using Cfg2 = periph::CHAN_CONFIG<2>;
  using Cfg3 = periph::CHAN_CONFIG<3>;

  Cfg0::write(Cfg0::SOURCE{std::uint8_t{0xAA}});
  Cfg2::write(Cfg2::SOURCE{std::uint8_t{0xCC}});

  EXPECT_EQ(Cfg0::read().get<Cfg0::SOURCE>(), 0xAAu);
  EXPECT_EQ(Cfg1::read().get<Cfg1::SOURCE>(), 0u);
  EXPECT_EQ(Cfg2::read().get<Cfg2::SOURCE>(), 0xCCu);
  EXPECT_EQ(Cfg3::read().get<Cfg3::SOURCE>(), 0u);
}

TEST_F(MmioTest, ClusterEightBitMemberIsByteStore) {
  std::memset(periphBytes(), 0xFF, kPeriphBytes);
  // CHAN_STATE<1> is at byte offset 0x58 — only that byte may change.
  periph::CHAN_STATE<1>::write(periph::CHAN_STATE<1>::VALUE{std::uint8_t{0x42}});

  EXPECT_EQ(periphBytes()[0x57], 0xFFu);
  EXPECT_EQ(periphBytes()[0x58], 0x42u);
  EXPECT_EQ(periphBytes()[0x59], 0xFFu);
}

TEST_F(MmioTest, ClusterMemberStorageTypesMatchSvd) {
  static_assert(std::is_same_v<periph::CHAN_CONFIG<0>::storage_type, std::uint32_t>);
  static_assert(std::is_same_v<periph::CHAN_STATE<0>::storage_type,  std::uint8_t>);
}

// --- Nested array inside cluster: 2D template <ClusterIndex, ArrayIndex> ----

TEST_F(MmioTest, NestedArrayAddressArithmetic) {
  // CHAN_SETPOINT<C, S> = 0x10000040 + C*0x10 + 0xC + S*0x4.
  EXPECT_EQ((periph::CHAN_SETPOINT<0, 0>::kAddr), 0x1000004Cu);
  EXPECT_EQ((periph::CHAN_SETPOINT<0, 1>::kAddr), 0x10000050u);
  EXPECT_EQ((periph::CHAN_SETPOINT<1, 0>::kAddr), 0x1000005Cu);
  EXPECT_EQ((periph::CHAN_SETPOINT<2, 1>::kAddr), 0x10000070u);
  EXPECT_EQ((periph::CHAN_SETPOINT<3, 1>::kAddr), 0x10000080u);
}

TEST_F(MmioTest, NestedArrayWritesAreCellIsolated) {
  using S00 = periph::CHAN_SETPOINT<0, 0>;
  using S01 = periph::CHAN_SETPOINT<0, 1>;
  using S10 = periph::CHAN_SETPOINT<1, 0>;
  using S11 = periph::CHAN_SETPOINT<1, 1>;

  S00::write(S00::POINT{0xAA000000u});
  S11::write(S11::POINT{0x000000BBu});

  EXPECT_EQ(S00::read().get<S00::POINT>(), 0xAA000000u);
  EXPECT_EQ(S01::read().get<S01::POINT>(), 0u);
  EXPECT_EQ(S10::read().get<S10::POINT>(), 0u);
  EXPECT_EQ(S11::read().get<S11::POINT>(), 0x000000BBu);
}

// --- Peripheral family: <derivedFrom> siblings -> templated class -----------

TEST_F(MmioTest, FamilyAddressesPickedFromInstanceTable) {
  EXPECT_EQ((regs::Port<1>::CTRL::kAddr), 0x10001000u);
  EXPECT_EQ((regs::Port<2>::CTRL::kAddr), 0x10001100u);
  EXPECT_EQ((regs::Port<3>::CTRL::kAddr), 0x10001200u);
  EXPECT_EQ((regs::Port<1>::DATA::kAddr), 0x10001004u);
  EXPECT_EQ((regs::Port<3>::DATA::kAddr), 0x10001204u);
}

TEST_F(MmioTest, FamilyWritesAreInstanceIsolated) {
  using P1 = regs::Port<1>;
  using P2 = regs::Port<2>;
  using P3 = regs::Port<3>;

  P1::CTRL::write(P1::CTRL::ENABLE{true}, P1::CTRL::MODE{std::uint8_t{0x5}});
  P3::DATA::write(P3::DATA::VALUE{0xDEADBEEFu});

  EXPECT_TRUE (P1::CTRL::read().get<P1::CTRL::ENABLE>());
  EXPECT_EQ   (P1::CTRL::read().get<P1::CTRL::MODE>(), 0x5u);
  EXPECT_FALSE(P2::CTRL::read().get<P2::CTRL::ENABLE>());
  EXPECT_EQ   (P2::DATA::read().get<P2::DATA::VALUE>(), 0u);
  EXPECT_EQ   (P3::DATA::read().get<P3::DATA::VALUE>(), 0xDEADBEEFu);
}

TEST_F(MmioTest, FamilyMemberStorageTypesMatchSvd) {
  static_assert(std::is_same_v<regs::Port<1>::CTRL::storage_type, std::uint32_t>);
  static_assert(std::is_same_v<regs::Port<2>::DATA::storage_type, std::uint32_t>);
}
